---

- name: Provisioning environment
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  roles:
   - role: cmprescott.chrome
     become: yes
   - role: angstwad.docker_ubuntu
     become: yes
   - role: tersmitten.pycharm
     become: yes
     pycharm_version: 2017.1.3
   - role: skype
   - role: dropbox
   - role: xcape
   - role: keyboard_layout
     become: yes
   - role: slack
     become: yes

  tasks:
    - name: Install packages
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - zsh
        - tmux
        - virtualbox
        - vagrant
        - pgadmin3
        - tig

    - name: "Add {{ user_name }} to docker group"
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
        shell: /bin/zsh

    - name: Install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      become: true
      become_user: sam

    - name: Get dotfiles
      git:
        repo: 'https://github.com/sluenenglish/dotfiles.git'
        dest: /home/sam/dotfiles
      become: true
      become_user: sam

    - name: Install dotfiles
      shell: bash /home/sam/dotfiles/install
