---

- name: Provisioning environment
  hosts: localhost
  become: true
  connection: local
  vars_files:
    - vars/main.yml
  roles:
   - role: cmprescott.chrome
   - role: interception

  tasks:
    - name: Install packages
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - zsh
        - tmux
        - virtualbox
        - vagrant
        - pgadmin3
        - tig

    - name: Install snap packages
      shell: snap install {{ item }} --classic
      become: true
      with_items:
        - pycharm-professional
        - docker
        - spotify

    - name: Ensure group "docker" exists
      group:
            name: docker    
            state: present

    - name: "Add {{ user_name }} to docker group"
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
        shell: /bin/zsh

    - name: Install Vundle
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '/home/sam/.vim/bundle/Vundle.vim'
      become_user: sam

    - name: Get dotfiles
      git:
        repo: 'git@github.com:sluenenglish/dotfiles.git'
        dest: /home/sam/dotfiles
      become_user: sam

    - name: Change shell
      shell: chsh -s $(which zsh) sam

    - name: Get base16 shell
      git:
        repo: 'https://github.com/chriskempson/base16-shell.git'
        dest: ~/.config/base16-shell
      become_user: sam

    - name: Install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      become: true
      become_user: sam

    - name: Install dotfiles
      shell: bash /home/sam/dotfiles/install
      become_user: sam

