---

- name: Provisioning environment
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/main.yml
  roles:
   - role: cmprescott.chrome
     become: yes
   - role: angstwad.docker_ubuntu
     become: yes
   - role: tersmitten.pycharm
     become: yes
     pycharm_version: 2017.1.3
   - role: skype
   - role: dropbox
   - role: xcape
   - role: keyboard_layout

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - zsh
        - tmux
        - virtualbox
        - vagrant
        - pgadmin3

    - name: "Add {{ user_name }} to docker group"
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
        shell: /bin/zsh
